### ISSUE TITLE
Admin level for chat commands

### ISSUE THREAD

**Issue by xorex** [Prisma501/CoppisAdditions#1]
On our server several levels of rights for administrators _(above 0)_. It will be great to be able to assign an administrator level to use some commands in the chat: _Waypoints, Move, Flyto, Protective Bubble_.

may be different levels for _locationtracking_, _locationtracking_, _Hostile reporting_ and _Advanced Claims_ too

**Comment by SylenThunder** [comment]
Late response, but don't use 0 as default for administrator. Only use that for the server owner. You have 998 other levels you can play with.
